version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"   # Expose for local dev, optional
    networks:
      - redis-net

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "5540:5540"   # Access UI at http://localhost:5540
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
